[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "build"
baseUrl = "https://diarmuid.dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200